name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment-pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npn install
        run: npm install
      - name: linter
        run: npm run eslint
      - name: buid & test
        run: npm run build & npm run test