name: Hello World

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Now it is
        run: |
          date
      - name: Directory commands
        run: |
          ls -l